---
name: Seungsu
surname: Lee
position: "B.S. degree student"
address: "School of CSE, Hanyang Univ."
phone: +82 10-3275-0644
profilepic: seungsu_pic.jpg
www: seungsu.shinyapps.io
email: "mqm00@hanyang.ac.kr"
twitter: Lee
github: github.com/mqm00
date: "May/01/2000"
aboutme: "Hello, my name is Seungsu Lee.\\newline I am majoring in computer software \\newline at Hanyang University.\\newline And also pursuing a minor in entrepreneurship \\newline convergence. My goal is to become a startup CEO"
output: vitae::moderncv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Some stuff about me

 * I am 24 years old.
 * I like to be active and work out. 
 * I enjoy weight training, running, etc. I've also recently gotten interested in mountain climbing and often go.
 * Marine Corps expires September 2021

# Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "High school", "2016-2018", "Gwang-ju high school", "Gyeonggi, Korea",
  "B.S. degree of Computer Software Engineering", "2019 ~", "Hanyang Univ.", "Seoul, Korea",
  "B.S. degree of entrepreneurship", "2023 ~", "Hanyang Univ.", "Seoul, Korea"
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

# Nobel Prizes

```{r}
tribble(
  ~Year, ~Type, ~Desc,
  1903, "Physics", "Awarded for her work on radioactivity with Pierre Curie and Henri Becquerel",
  1911, "Chemistry", "Awarded for the discovery of radium and polonium"
) %>% 
  brief_entries(
    glue::glue("Nobel Prize in {Type}"),
    Year, 
    Desc
  )
```

# Skills

 * C, Java, Python, R
 * Flutter, Shiny
 * MySQL
